### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by daiki-mrt** [daiki-mrt/protospace-31052#1]
# URL
https://protospace-31052.herokuapp.com/

**Comment by kaho0919** [comment]
森田さん、ご提出ありがとうございます！お待たせしました。
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

・画像なしでプロトタイプを投稿した時、投稿画面に遷移せず、エラー画面（ページ見つかりませんの画面）が出てしまう。
→キャッチコピーなどが入力されていない時と同じような画面（投稿画面のままになる）になるようにしましょう。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by daiki-mrt** [comment]
レビューありがとうございます！
修正しましたので、ご確認お願いします。

**事象**
①プロトタイプ新規投稿失敗する、new.html.erbへレンダリング。
②レンダリング後に投稿しようとすると、paramsが無いというエラー。
確認すると、2回目の投稿ではparams内にprototypeというキーが無かった。
→privateメソッドのrequire(:prototype)で引っかかったと思われる。

**対応**
createアクションでのインスタンス生成をprototype→@prototypeへ変更。
理由としては、new.html.erbで使用するフォームに@prototypeを代入しているため。

**Comment by MasaakiTanabashi** [comment]
森田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
